/// The Omarchy keyboard shortcuts, as published at
/// <https://omarchy.org/manual/hotkeys/>.
///
/// Baked in rather than fetched. This is a cheat sheet on a wall: it has to be
/// right when the network is not, and scraping a documentation page would put
/// the panel one redesign away from showing nothing. The cost is that it goes
/// stale silently, so [omarchyHotkeysFetched] records when it was taken and the
/// widget prints it.
///
/// Transcribed verbatim, including the sections' own wording. Where the page
/// uses a bold sub-heading inside a section — Tmux's panes, windows and
/// sessions; Neovim's sidebar — that becomes a section of its own here, so a
/// screenful stays a screenful.
library;

/// One shortcut and what it does.
class Hotkey {
  const Hotkey(this.keys, this.action);

  /// The combination, in the source's own notation: parts joined by ` + `,
  /// alternatives by ` or `.
  final String keys;

  final String action;
}

/// A named group of shortcuts.
class HotkeySection {
  const HotkeySection(this.title, this.keys);

  final String title;
  final List<Hotkey> keys;
}

/// When the list below was taken from the manual.
const String omarchyHotkeysFetched = '1 September 2026';

const List<HotkeySection> omarchyHotkeys = [
  HotkeySection('Navigating', [
    Hotkey('Super + Space', 'Omarchy menu (apps and everything else)'),
    Hotkey('Super + Alt + Space', 'Apps menu'),
    Hotkey('Super + Escape', 'System menu (suspend, restart, etc)'),
    Hotkey('Super + Ctrl + L', 'Lock computer'),
    Hotkey('Super + W or Super + Q', 'Close window'),
    Hotkey('Ctrl + Alt + Del', 'Close all windows'),
    Hotkey('Super + T', 'Toggle window between tiling/floating'),
    Hotkey('Super + J', 'Toggle window position (horizontal/vertical)'),
    Hotkey('Super + O', 'Toggle popping window into sticky\'n\'floating'),
    Hotkey('Super + L', 'Toggle between dwindle and scrolling layout'),
    Hotkey('Super + P', 'Toggle pseudo window style (natural v stretch)'),
    Hotkey('Super + F', 'Go full screen'),
    Hotkey('Super + Alt + F', 'Go full width'),
    Hotkey('Super + Ctrl + F', 'Go full screen inside window'),
    Hotkey('Super + 1/2/3/4', 'Jump to specific workspace'),
    Hotkey('Super + Tab', 'Jump to next workspace'),
    Hotkey('Super + Shift + Tab', 'Jump to previous workspace'),
    Hotkey('Super + Ctrl + Tab', 'Jump to former workspace'),
    Hotkey('Super + Shift + 1/2/3/4', 'Move window to workspace'),
    Hotkey('Super + Shift + Alt + 1/2/3/4', 'Move window to workspace without following'),
    Hotkey('Super + S or Super + Grave', 'Toggle scratchpad'),
    Hotkey('Super + Alt + S or Super + Shift + Grave', 'Move window to scratchpad'),
    Hotkey('Super + Shift + Alt + Arrows', 'Move workspaces to directional monitor'),
    Hotkey('Super + Arrow', 'Move focus to window in direction of arrow'),
    Hotkey('Super + Shift + Arrow', 'Swap window with another in direction of arrow'),
    Hotkey('Super + Minus', 'Expand window left'),
    Hotkey('Super + Equal', 'Shrink window left'),
    Hotkey('Super + Shift + Minus', 'Shrink window up'),
    Hotkey('Super + Shift + Equal', 'Expand window down'),
    Hotkey('Super + Alt + Minus/Equal', 'Same resizing in smaller steps'),
    Hotkey('Super + Ctrl + Minus/Equal', 'Same resizing in bigger steps'),
    Hotkey('Super + Alt + Home', 'Save window width'),
    Hotkey('Super + Home', 'Restore saved window width'),
    Hotkey('Super + Left Mouse', 'Drag window around'),
    Hotkey('Super + Right Mouse', 'Resize window'),
    Hotkey('Super + Scroll Wheel', 'Scroll through workspaces'),
    Hotkey('Super + G', 'Toggle window grouping'),
    Hotkey('Super + Alt + G', 'Move window out of grouping'),
    Hotkey('Super + Alt + Tab', 'Cycle between windows in grouping'),
    Hotkey('Super + Alt + Shift + Tab', 'Cycle backward between windows in grouping'),
    Hotkey('Super + Alt + 1/2/3/4/5', 'Jump to specific window in grouping'),
    Hotkey('Super + Alt + Arrow', 'Move window into grouping in direction of arrow'),
    Hotkey('Super + Ctrl + Left/Right', 'Move between windows inside a tiling group'),
    Hotkey('Super + Ctrl + Z', 'Zoom in on screen (repeat for more zoom)'),
    Hotkey('Super + Ctrl + Alt + Z', 'Zoom fully out from screen'),
    Hotkey('Super + /', 'Step forward through monitor scaling options'),
    Hotkey('Super + Alt + /', 'Step backward through monitor scaling options'),
    Hotkey('Alt + Tab', 'Cycle forward through windows on the active workspace'),
    Hotkey('Alt + Shift + Tab', 'Cycle backward through windows on the active workspace'),
    Hotkey('Ctrl + Alt + Tab', 'Cycle focus forward through monitors'),
    Hotkey('Ctrl + Alt + Shift + Tab', 'Cycle focus backwards through monitors'),
  ]),
  HotkeySection('System controls', [
    Hotkey('Super + Ctrl + A', 'Audio panel'),
    Hotkey('Super + Ctrl + B', 'Bluetooth panel'),
    Hotkey('Super + Ctrl + W', 'Wifi/network panel'),
    Hotkey('Super + Ctrl + D', 'Display panel'),
    Hotkey('Super + Ctrl + P', 'Power panel'),
    Hotkey('Super + Ctrl + Alt + D', 'Calendar panel'),
    Hotkey('Super + Ctrl + 1-9', 'Toggle bar panel by position'),
    Hotkey('Super + Ctrl + S', 'Share menu (via LocalSend)'),
    Hotkey('Super + Ctrl + T', 'Activity (btop)'),
    Hotkey('Super + Ctrl + C', 'Capture controls (screenshot/-recording/picker)'),
    Hotkey('Super + Ctrl + O', 'Toggle menu'),
    Hotkey('Super + Ctrl + H', 'Hardware menu'),
    Hotkey('Super + Ctrl + Q', 'Calculator'),
    Hotkey('Super + Ctrl + E', 'Emoji picker'),
    Hotkey('Super + Ctrl + .', 'Transcode media'),
    Hotkey('Super + Shift + Ctrl + A', 'Pick an AI agent'),
  ]),
  HotkeySection('Adjustments', [
    Hotkey('Shift + Brightness Up', 'Maximum screen brightness'),
    Hotkey('Shift + Brightness Down', 'Minimum screen brightness'),
    Hotkey('Alt + Brightness Up/Down', 'Precise 1% brightness changes'),
    Hotkey('Alt + Volume Up/Down', 'Precise 1% volume changes'),
    Hotkey('Keyboard Brightness Up/Down', 'Keyboard backlight brighter/dimmer'),
    Hotkey('Keyboard Backlight', 'Cycle the keyboard backlight levels'),
    Hotkey('Alt + Play', 'Next track'),
    Hotkey('Alt + Shift + Play', 'Previous track'),
  ]),
  HotkeySection('Launching apps', [
    Hotkey('Super + Return', 'Terminal'),
    Hotkey('Super + Alt + Return', 'Tmux terminal'),
    Hotkey('Super + Ctrl + Return', 'Herdr (agent manager)'),
    Hotkey('Super + Shift + Return', 'Browser'),
    Hotkey('Super + Shift + Alt + B', 'Browser (private/incognito)'),
    Hotkey('Super + Shift + F', 'File manager'),
    Hotkey('Super + Shift + Alt + F', 'File manager in cwd of terminal'),
    Hotkey('Super + Shift + M', 'Music (Spotify)'),
    Hotkey('Super + Shift + Alt + M', 'Music (cliamp)'),
    Hotkey('Super + Shift + /', 'Password manager (1password)'),
    Hotkey('Super + Shift + N', 'Editor (Neovim)'),
    Hotkey('Super + Shift + C', 'Calendar (HEY)'),
    Hotkey('Super + Shift + E', 'Email (HEY)'),
    Hotkey('Super + Shift + Alt + E', 'New email (HEY)'),
    Hotkey('Super + Shift + A', 'AI (ChatGPT)'),
    Hotkey('Super + Shift + Alt + A', 'AI (Grok)'),
    Hotkey('Super + Shift + G', 'Messenger (Signal)'),
    Hotkey('Super + Shift + P', 'Google Photos'),
    Hotkey('Super + Shift + S', 'Google Maps'),
    Hotkey('Super + Shift + Alt + G', 'Messenger (WhatsApp)'),
    Hotkey('Super + Shift + Ctrl + G', 'Messenger (Google)'),
    Hotkey('Super + Shift + D', 'Docker (LazyDocker)'),
    Hotkey('Super + Shift + O', 'Obsidian'),
    Hotkey('Super + Shift + W', 'Writing (Omawrite)'),
    Hotkey('Super + Shift + X', 'X'),
    Hotkey('Super + Shift + Alt + X', 'X Compose'),
    Hotkey('Super + Shift + Y', 'YouTube'),
  ]),
  HotkeySection('Universal clipboard', [
    Hotkey('Super + C', 'Copy'),
    Hotkey('Super + X', 'Cut (not in terminal)'),
    Hotkey('Super + V', 'Paste'),
    Hotkey('Super + Ctrl + V', 'Clipboard manager'),
  ]),
  HotkeySection('Capture', [
    Hotkey('Super + Ctrl + C', 'Capture menu (for keyboards w/o PrintScr button)'),
    Hotkey('Print Screen', 'Screenshot'),
    Hotkey('Alt + Print Screen', 'Screenrecord'),
    Hotkey('Super + Print Screen', 'Color picker'),
    Hotkey('Super + Ctrl + Print Screen', 'Text extraction to clipboard'),
    Hotkey('Super + Alt + [', 'Make webcam overlay smaller while recording'),
    Hotkey('Super + Alt + ]', 'Make webcam overlay larger while recording'),
    Hotkey('Alt + Shift + L', 'Copy current URL from webapp or Chromium'),
    Hotkey('Alt + Shift + D', 'Download the video on the current page to ~/Videos'),
    Hotkey('Super + Ctrl + X', 'Start/stop dictation (requires Install > AI > Dictation)'),
    Hotkey('F9', 'Push-to-talk dictation (requires Install > AI > Dictation)'),
  ]),
  HotkeySection('Notifications', [
    Hotkey('Super + ,', 'Dismiss latest notification'),
    Hotkey('Super + Shift + ,', 'Dismiss all notifications'),
    Hotkey('Super + Ctrl + ,', 'Toggle silencing notifications'),
    Hotkey('Super + Alt + ,', 'Invoke most recent notification'),
    Hotkey('Super + Shift + Alt + ,', 'Open notification history'),
  ]),
  HotkeySection('Style', [
    Hotkey('Super + Ctrl + Shift + Space', 'Pick a new theme'),
    Hotkey('Super + Ctrl + Space', 'Pick theme background'),
    Hotkey('Super + Backspace', 'Toggle transparency on a window'),
    Hotkey('Super + Ctrl + Backspace', 'Toggle single-window square aspect'),
  ]),
  HotkeySection('Toggles', [
    Hotkey('Super + Ctrl + I', 'Toggle locking on idle'),
    Hotkey('Super + Ctrl + N', 'Toggle nightlight display temperature'),
    Hotkey('Super + Ctrl + Delete', 'Toggle laptop display on/off'),
    Hotkey('Super + Ctrl + Alt + Delete', 'Toggle laptop display mirroring'),
    Hotkey('Super + Shift + Space', 'Toggle the top bar'),
    Hotkey('Shift + Mute', 'Switch to next audio output'),
    Hotkey('Shift + Play', 'Switch to next media source'),
    Hotkey('Super + Shift + Backspace', 'Toggle window gaps'),
  ]),
  HotkeySection('Reminders', [
    Hotkey('Super + Ctrl + R', 'Set a reminder'),
    Hotkey('Super + Ctrl + Alt + R', 'See all reminders'),
    Hotkey('Super + Ctrl + Shift + R', 'Clear all reminders'),
  ]),
  HotkeySection('Notices', [
    Hotkey('Super + Ctrl + Alt + T', 'Show time as notification'),
    Hotkey('Super + Ctrl + Alt + B', 'Show battery as notification'),
    Hotkey('Super + Ctrl + Alt + W', 'Toggle weather as notification'),
  ]),
  HotkeySection('Tmux — panes', [
    Hotkey('Prefix + v', 'Split pane beside (vertical)'),
    Hotkey('Prefix + h', 'Split pane below (horizontal)'),
    Hotkey('Prefix + x', 'Kill pane'),
    Hotkey('Prefix + z', 'Toggle pane zoom (fullscreen)'),
    Hotkey('Alt + Enter', 'Split pane below (no prefix)'),
    Hotkey('Alt + Shift + Enter', 'Split pane beside (no prefix)'),
    Hotkey('Alt + Escape', 'Kill pane (no prefix)'),
    Hotkey('Ctrl + Alt + Arrows', 'Move between panes'),
    Hotkey('Ctrl + Alt + Shift + Arrows', 'Resize panes'),
  ]),
  HotkeySection('Tmux — windows and sessions', [
    Hotkey('Prefix + c', 'New window'),
    Hotkey('Prefix + k', 'Kill window'),
    Hotkey('Prefix + r', 'Rename window'),
    Hotkey('Alt + 1-9', 'Go to specific window'),
    Hotkey('Alt + Arrow Left/Right', 'Move between windows'),
    Hotkey('Alt + Shift + Arrow Left/Right', 'Move window left/right'),
    Hotkey('Prefix + C', 'New session'),
    Hotkey('Prefix + K', 'Kill session'),
    Hotkey('Prefix + R', 'Rename session'),
    Hotkey('Prefix + N', 'Next session'),
    Hotkey('Prefix + P', 'Previous session'),
    Hotkey('Alt + Arrow Up/Down', 'Move between sessions'),
    Hotkey('Prefix + s', 'List sessions'),
    Hotkey('Prefix + d', 'Detach from session'),
  ]),
  HotkeySection('Tmux — copy mode and general', [
    Hotkey('Prefix + [', 'Enter copy mode'),
    Hotkey('v', 'Begin selection (in copy mode)'),
    Hotkey('y', 'Copy selection (in copy mode)'),
    Hotkey('Prefix + q', 'Reload config'),
    Hotkey('Prefix + ?', 'Show Tmux keybindings'),
    Hotkey('Prefix + :', 'Command prompt'),
  ]),
  HotkeySection('Ghostty terminal', [
    Hotkey('Ctrl + Shift + E', 'New split below'),
    Hotkey('Ctrl + Shift + O', 'New split besides'),
    Hotkey('Ctrl + Alt + Arrows', 'Move between splits'),
    Hotkey('Super + Ctrl + Shift + Arrows', 'Resize split by 10 lines'),
    Hotkey('Super + Ctrl + Shift + Alt + Arrows', 'Resize split by 100 lines'),
    Hotkey('Ctrl + Shift + T', 'New tab'),
    Hotkey('Ctrl + Shift + Arrows', 'Move between tabs'),
    Hotkey('Alt + Numbers', 'Go to specific tab'),
    Hotkey('Shift + Pg Up/Down', 'Scroll the history'),
    Hotkey('Ctrl + Left mouse', 'Open link in browser'),
  ]),
  HotkeySection('File manager', [
    Hotkey('Ctrl + L', 'Go to path'),
    Hotkey('Space', 'Preview file (arrows navigate)'),
    Hotkey('Backspace', 'Go back one folder'),
  ]),
  HotkeySection('Neovim (lazyvim)', [
    Hotkey('Space', 'Show command options'),
    Hotkey('Space Space', 'Open file via fuzzy search'),
    Hotkey('Space E', 'Toggle sidebar'),
    Hotkey('Space G G', 'Show git controls'),
    Hotkey('Space S G', 'Search file content'),
    Hotkey('Ctrl + W W', 'Jump between sidebar and editor'),
    Hotkey('Ctrl + Left/right arrow', 'Change size of sidebar'),
    Hotkey('Shift + H', 'Go to left file tab'),
    Hotkey('Shift + L', 'Go to right file tab'),
    Hotkey('Space B D', 'Close file tab'),
  ]),
  HotkeySection('Neovim — in the sidebar', [
    Hotkey('A', 'Add new file in parent dir'),
    Hotkey('Shift + A', 'Add new subdir in parent dir'),
    Hotkey('D', 'Delete highlighted file/dir'),
    Hotkey('M', 'Move highlighted file/dir'),
    Hotkey('R', 'Rename highlighted file/dir'),
    Hotkey('?', 'Show help for all commands'),
  ]),
  HotkeySection('Quick emojis', [
    Hotkey('CapsLock M S', '😄 smile'),
    Hotkey('CapsLock M C', '😂 cry'),
    Hotkey('CapsLock M L', '😍 love'),
    Hotkey('CapsLock M V', '✌️ victory'),
    Hotkey('CapsLock M H', '❤️ heart'),
    Hotkey('CapsLock M Y', '👍 yes'),
    Hotkey('CapsLock M N', '👎 no'),
    Hotkey('CapsLock M F', '🖕 fuck'),
    Hotkey('CapsLock M W', '🤞 wish'),
    Hotkey('CapsLock M R', '🤘 rock'),
    Hotkey('CapsLock M K', '😘 kiss'),
    Hotkey('CapsLock M E', '🙄 eyeroll'),
    Hotkey('CapsLock M I', '😉 wink'),
    Hotkey('CapsLock M P', '🙏 pray'),
    Hotkey('CapsLock M D', '🤤 drool'),
    Hotkey('CapsLock M M', '💰 money'),
    Hotkey('CapsLock M X', '🎉 xellebrate'),
    Hotkey('CapsLock M 1', '💯 100%'),
    Hotkey('CapsLock M T', '🥂 toast'),
    Hotkey('CapsLock M O', '👌 ok'),
    Hotkey('CapsLock M G', '👋 greeting'),
    Hotkey('CapsLock M A', '💪 arm'),
    Hotkey('CapsLock M B', '🤯 blowing'),
  ]),
  HotkeySection('Quick completions', [
    Hotkey('CapsLock Space Space', '— (mdash)'),
    Hotkey('CapsLock Space N', 'Your name (as entered on setup)'),
    Hotkey('CapsLock Space E', 'Your email (as entered on setup)'),
  ]),
];
