/// Attribution data shown on the About screen.
///
/// Keep this in sync with the "Third-party libraries" and "Credits and sources"
/// sections of the README — both are generated from the same facts.
library;

class Credit {
  final String name;
  final String purpose;
  final String licence;
  final String url;

  const Credit({
    required this.name,
    required this.purpose,
    required this.licence,
    required this.url,
  });
}

/// Dart/Flutter packages this app depends on directly.
const List<Credit> kDartPackages = [
  Credit(
    name: 'Flutter',
    purpose: 'UI toolkit the whole app is built on',
    licence: 'BSD-3-Clause',
    url: 'https://github.com/flutter/flutter',
  ),
  Credit(
    name: 'provider',
    purpose: 'State management and dependency injection',
    licence: 'MIT',
    url: 'https://github.com/rrousselGit/provider',
  ),
  Credit(
    name: 'dio',
    purpose: 'HTTP client for the Immich and weather APIs',
    licence: 'MIT',
    url: 'https://github.com/cfug/dio',
  ),
  Credit(
    name: 'cached_network_image',
    purpose: 'Images with auth headers and caching',
    licence: 'MIT',
    url: 'https://github.com/Baseflow/flutter_cached_network_image',
  ),
  Credit(
    name: 'flutter_cache_manager',
    purpose: 'On-disk cache, relocated to the NVMe',
    licence: 'MIT',
    url: 'https://github.com/Baseflow/flutter_cache_manager',
  ),
  Credit(
    name: 'file',
    purpose: 'Filesystem abstraction for the custom cache',
    licence: 'MIT',
    url: 'https://github.com/google/file.dart',
  ),
  Credit(
    name: 'media_kit',
    purpose: 'Video playback and playback-speed control',
    licence: 'MIT',
    url: 'https://github.com/media-kit/media-kit',
  ),
  Credit(
    name: 'media_kit_video',
    purpose: 'Video render surface',
    licence: 'MIT',
    url: 'https://pub.dev/packages/media_kit_video',
  ),
  Credit(
    name: 'media_kit_libs_video',
    purpose: 'Native video dependencies',
    licence: 'MIT',
    url: 'https://pub.dev/packages/media_kit_libs_video',
  ),
  Credit(
    name: 'path',
    purpose: 'Path joining for cache locations',
    licence: 'BSD-3-Clause',
    url: 'https://github.com/dart-lang/path',
  ),
  Credit(
    name: 'flutter_lints',
    purpose: 'Lint rules (development only)',
    licence: 'BSD-3-Clause',
    url: 'https://pub.dev/packages/flutter_lints',
  ),
];

/// Libraries provided by the operating system.
const List<Credit> kSystemLibraries = [
  Credit(
    name: 'mpv / libmpv',
    purpose: 'Video decoding behind media_kit',
    licence: 'LGPL-2.1+',
    url: 'https://mpv.io',
  ),
  Credit(
    name: 'GTK 3',
    purpose: "Flutter's Linux embedder window",
    licence: 'LGPL-2.1+',
    url: 'https://www.gtk.org',
  ),
];

/// Network services the app talks to.
const List<Credit> kServices = [
  Credit(
    name: 'Immich',
    purpose: 'Your own photo and video server',
    licence: 'AGPL-3.0',
    url: 'https://immich.app',
  ),
  Credit(
    name: 'Open-Meteo',
    purpose: 'Weather forecast — no API key required',
    licence: 'CC BY 4.0 · free for non-commercial use',
    url: 'https://open-meteo.com',
  ),
  Credit(
    name: 'postcodes.io',
    purpose: 'UK postcode to coordinates lookup',
    licence: 'MIT · data under OGL v3',
    url: 'https://postcodes.io',
  ),
];

/// Code in this project that came from, or was adapted from, elsewhere.
class SourceCredit {
  final String what;
  final String detail;
  final String? url;

  const SourceCredit({required this.what, required this.detail, this.url});
}

const List<SourceCredit> kSourceCredits = [
  SourceCredit(
    what: 'Flutter project scaffolding',
    detail:
        'linux/runner/*, .metadata, analysis_options.yaml and the initial '
        'main.dart were generated by "flutter create" and then modified — '
        'notably my_application.cc, changed to start fullscreen and '
        'borderless. Flutter SDK, BSD-3-Clause.',
    url: 'https://github.com/flutter/flutter',
  ),
  SourceCredit(
    what: 'Cache filesystem',
    detail:
        '_NvmeFileSystem in services/media_cache.dart is modelled on '
        "flutter_cache_manager's IOFileSystem (MIT), changed to store files "
        'under a fixed directory instead of the system temp directory.',
    url:
        'https://github.com/Baseflow/flutter_cache_manager/blob/develop/lib/src/storage/file_system/file_system_io.dart',
  ),
  SourceCredit(
    what: 'Weather code mapping',
    detail:
        'The weather-code descriptions and icon/colour mapping follow the WMO '
        'weather-code table as published in the Open-Meteo API documentation.',
    url: 'https://open-meteo.com/en/docs',
  ),
  SourceCredit(
    what: 'Immich API usage',
    detail:
        'Derived from the Immich API documentation together with probing a '
        'live v3 server — in particular that album contents come from '
        'POST /api/search/metadata, and that the Locked Folder requires a '
        'session token rather than an API key.',
    url: 'https://immich.app/docs/api',
  ),
  SourceCredit(
    what: 'Material Design icons',
    detail: 'Bundled with Flutter. Apache-2.0.',
    url: 'https://fonts.google.com/icons',
  ),
];
